### PR TITLE
Statically ban `return continue eval("...")`

### PR DESCRIPTION
**Pull request by littledan**
Closes #14

### CODE REVIEW

**Comment by bterlson** [comment]
Sounds good!

**Comment by claudepache** [comment]
That looks buggy to me:
- StringValue is not defined for |MemberExpression|s;
- It does not handle the case `continue (((eval)))("...")`, which is still a direct eval (unless a nontrivial definition of StringValue is provided),

I think that some more static analysis is needed. Something like the following:
- It is a SyntaxError if MayBeDirectEvalReference of |MemberExpression| is **true**.

And:

## Static semantics: MayBeDirectEvalReference

```
Identifier : IdentifierName

    1. If StringValue of IdentifierName is "eval" return true.
    2. Return false.


CoverParenthesizedExpressionAndArrowParameterList[Yield] :  (  Expression[In, ?Yield]  )

    1. Return MayBeDirectEvalReference of Expression[In, ?Yield].

SomeNonTerminal : SomeOtherNonTerminal

    1. Return MayBeDirectEvalReference of SomeOtherNonTerminal.

Anything else

    1. Return false.        
```

**Comment by littledan** [comment]
I guess we have more detailed cases like `continue (1, eval)("...")` as well. We implementations statically detect direct eval possibilities, so this should be possible somehow, but it's not clear how the spec text should be worded. @claudepache wanna write a PR?

**Comment by claudepache** [comment]
> I guess we have more detailed cases like continue (1, eval)("...") as well.
> 
> `(1, eval)` triggers an indirect eval. 
> 
> implementations statically detect direct eval possibilities, so this should be possible somehow, but it's not clear how the spec text should be worded. @claudepache wanna write a PR?
> 
> Detailing `MayBeDirectEvalReference` for each  production, following the model of `IsValidSimpleAssignmentTarget`, is easy but tedious. However, one could instead use a formulation similar to what is done for the `delete` operator (12.5.3.1). OK, I'll write a PR soon.

**Pull request merged**
